name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # Change this to your default branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Hostinger
        uses: samuelmeuli/action-scp@v2
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          port: ${{ secrets.HOSTINGER_PORT }}  # Add this line to specify the port
          source: "."
          target: "/files/public_html"  # Adjust the target path
