name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # Change this to your default branch if needed
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Hostinger
        uses: appleboy/scp-action@v0.1.4  # Use this action instead
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}  # Add your SSH private key here
          port: ${{ secrets.HOSTINGER_PORT }}
          source: "."
          target: "/home/u962339350/domains/color-uncover-com-228880.hostingersite.com/public_html"
